Repository unovue/inspira-ui, pull requests merged in 2024-10, with the labels that each got.

#5 fix: list overlap
  components/content/inspira/ui/animated-list/AnimatedList.vue
Labels: enhancement

#13 feat: add HyperText component
  components/content/inspira/examples/HyperTextDemo.vue
  components/content/inspira/ui/hyper-text/HyperText.vue
  content/2.components/0.all.md
  content/2.components/hyper-text.md
Labels: add-request-feature

#14 feat: text reveal card component
  components/content/inspira/examples/TextRevealDemo.vue
  components/content/inspira/ui/text-reveal-card/TextRevealCard.vue
  components/content/inspira/ui/text-reveal-card/TextRevealStars.vue
  content/2.components/0.all.md
  content/2.components/text-reveal-card.md
Labels: add-request-feature

#20 chore: add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#43 Feature/progress bar
  components/content/inspira/examples/animated-circular-progressbar/AnimatedCircularProgressBarDemo.vue
  components/content/inspira/ui/animated-circular-progressbar/AnimatedCircularProgressBar.vue
  content/2.components/animated-circular-progressbar.md
Labels: add-request-feature
